set nocompatible
filetype off

let $VIMRUNTIME='/usr/share/vim/vim74/'
set rtp+=~/.vim/bundle/Vundle.vim

execute pathogen#infect()

filetype plugin indent on

set shell=/bin/bash\ -l

"remap leader to <space>; \ is out of the way
let mapleader = "\<Space>"

"j then k to return to normal mode
inoremap jk <ESC>
nnoremap ; :!

nnoremap <Home> gg
nnoremap <End> G

"I don't like hitting shift
nnoremap <leader>j :
"This line is my favorite
nnoremap <leader>t :tabnew<space>
nnoremap <leader>w :w<CR>
nnoremap <leader>q :q<CR>
nnoremap <leader>e :e<CR>
nnoremap <leader>p :set paste!<CR>
nnoremap <leader>h :set hlsearch!<CR>
"Switch tabs fast
"TODO If there are only, for instance, 6 tabs <leader>8 should go to the last
nnoremap <leader>1 1gt
nnoremap <leader>2 2gt
nnoremap <leader>3 3gt
nnoremap <leader>4 4gt
nnoremap <leader>5 5gt
nnoremap <leader>6 6gt
nnoremap <leader>7 7gt
nnoremap <leader>8 8gt
"9 to move to last tab (like firefox etc)
nnoremap <leader>9 :tablast<CR>

"I don't like have to hit shift to switch tabs backwards
nnoremap gr gT

"shift can be annoying
command W w
command Q q
command WQ wq
command Wq wq

nmap j gj
nmap k gk

"use system clipboard
":set clipboard=unnamed

set runtimepath^=~/.vim/bundle/ctrlp.vim
let g:ctrlp_match_window_bottom = 0
let g:ctrlp_match_window_reversed = 0
let g:ctrlp_custom_ignore = '\v\~$|\.(o|swp|pyc|wav|mp3|ogg|blend)$|(^|[/\\])\.(hg|git|bzr)($|[/\\])|__init__\.py'
let g:ctrlp_working_path_mode = 0
let g:ctrlp_dotfiles = 0
let g:ctrlp_switch_buffer = 0

"For emmet
let g:user_emmet_leader_key='<C-G>'

"Basic settings"
set backspace=indent,eol,start "Makes backspace work"
set history=500 "Sets undo history size"
set ruler "Sets up status bar"
set number "Turns on line numbering"
set tabstop=4 "Sets indent size of tabs"
set softtabstop=4 "Soft tabs"
set expandtab "Tabs suck. Spaces rule."
set shiftwidth=4 "Sets auto-indent size"
set laststatus=2 "Always keeps the status bar active"
set autoindent "Turns on auto-indenting"
set copyindent "Copy the previous indentation on autoindenting"
set smartindent "Remembers previous indent when creating new lines"
set wildignorecase "Ignore case while autocompletting search results"

au BufNewFile,BufRead *.js,*.jsx*,*.rb,*.html,*.xml :setlocal sw=2 ts=2 sts=2 " Two spaces for js/ruby/etc files "
au FileType make setlocal noexpandtab

au BufNewFile,BufRead *.jade,*.coffee :setlocal autoindent noexpandtab ts=4 sw=4 " Coffee setup"

"set nu
"set shiftwidth=4
"set tabstop=4

set fdm=manual
set mouse=a

syntax on

filetype plugin indent on

au BufRead,BufNewFile *.json set filetype=javascript
au BufRead,BufNewFile *.jsbundle set filetype=javascript

let g:haddock_browser="open"
let g:haddock_browser_callformat = "%s %s"

