set nocompatible
filetype off

let $VIMRUNTIME='/usr/share/vim/vim74/'

call plug#begin('~/.vim/plugged')

"fuzzyfinding
Plug '/usr/local/opt/fzf' | Plug 'junegunn/fzf.vim'

"colors
Plug 'ap/vim-css-color'

"Airline
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

call plug#end()

execute pathogen#infect()

filetype plugin indent on

set shell=/bin/bash\ -l

"remap leader to <space>; \ is out of the way
let mapleader = "\<Space>"

"j then k to return to normal mode
inoremap jk <ESC>
nnoremap ; :!

nnoremap <Home> gg
nnoremap <End> G

nnoremap <leader>w :w<CR>
nnoremap <leader>e :e<CR>
nnoremap <leader>p :set paste!<CR>
nnoremap <leader>h :set hlsearch!<CR>
"This line is my favorite
nnoremap <leader>t :Files<CR>
nnoremap <leader>b :buffers<CR>:buffer<Space>
"TODO close vim if last buffer
nnoremap <leader>q :bp <BAR> bd #<CR>
nnoremap <C-l> :bnext<CR>
nnoremap <C-h> :bprevious<CR>
"Switch buffers quickly
"TODO If there are only, for instance, 6 buffers <leader>8 should go to the last
nnoremap <leader>1 :b 1<CR>
nnoremap <leader>2 :b 2<CR>
nnoremap <leader>3 :b 3<CR>
nnoremap <leader>4 :b 4<CR>
nnoremap <leader>5 :b 5<CR>
nnoremap <leader>6 :b 6<CR>
nnoremap <leader>7 :b 7<CR>
nnoremap <leader>8 :b 8<CR>
"9 should move to last buffer (like firefox etc)
nnoremap <leader>9 :b 9<CR>

"I don't like have to hit shift to switch tabs backwards
nnoremap gr gT

"shift can be annoying
command W w
command Q q
command WQ wq
command Wq wq

nmap j gj
nmap k gk

"more memorable keys for scrolling screen
map <C-j> <C-e>
map <C-k> <C-y>

"use system clipboard
":set clipboard=unnamed

set runtimepath^=~/.vim/bundle/ctrlp.vim
let g:ctrlp_match_window_bottom = 0
let g:ctrlp_match_window_reversed = 0
let g:ctrlp_custom_ignore = '\v\~$|\.(o|swp|pyc|wav|mp3|ogg|blend)$|(^|[/\\])\.(hg|git|bzr)($|[/\\])|__init__\.py'
let g:ctrlp_working_path_mode = 0
let g:ctrlp_dotfiles = 0
let g:ctrlp_switch_buffer = 0

"For emmet
let g:user_emmet_leader_key='<C-G>'

"Airline configuration

" Enable the list of buffers
let g:airline#extensions#tabline#enabled = 1
" Show just the filename
let g:airline#extensions#tabline#fnamemod = ':t'


"Basic settings"
set hidden
set backspace=indent,eol,start "Makes backspace work"
set history=500 "Sets undo history size"
set ruler "Sets up status bar"
set number "Turns on line numbering"
set tabstop=4 "Sets indent size of tabs"
set softtabstop=4 "Soft tabs"
set expandtab "Tabs suck. Spaces rule."
set shiftwidth=4 "Sets auto-indent size"
set laststatus=2 "Always keeps the status bar active"
set autoindent "Turns on auto-indenting"
set copyindent "Copy the previous indentation on autoindenting"
set smartindent "Remembers previous indent when creating new lines"
set wildignorecase "Ignore case while autocompletting search results"

au BufNewFile,BufRead *.js,*.jsx*,*.rb,*.html,*.xml :setlocal sw=2 ts=2 sts=2 " Two spaces for js/ruby/etc files "
au FileType make setlocal noexpandtab

au BufNewFile,BufRead *.jade,*.coffee :setlocal autoindent noexpandtab ts=4 sw=4 " Coffee setup"

"set nu
"set shiftwidth=4
"set tabstop=4

set fdm=manual
set mouse=a

syntax on

filetype plugin indent on

au BufRead,BufNewFile *.json set filetype=javascript
au BufRead,BufNewFile *.jsbundle set filetype=javascript

let g:haddock_browser="open"
let g:haddock_browser_callformat = "%s %s"

