# Environment Vars
export EDITOR=vim
export PS1='\$ '
export HISTSIZE=50000

export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/lib/"
export qtpath="/usr/local/Cellar/qt@4/4.8.7_3"

export NODE_ENV=local
export DEBUG='sketchdeck*'

# Time saving aliases
alias bashrc='$EDITOR ~/.bash_profile'
alias vimrc='$EDITOR ~/.vimrc'
alias py='python3'
alias h='http-server'
alias n='ngrok http 8080 -host-header="localhost:8080"'
# Git aliases
alias gs='git status'
alias gd='git diff -D'
alias gds='git diff -D --staged'
# What did my last commit change?
alias gdl='git diff HEAD~ HEAD'
alias gl='git -c color.ui=always log --oneline | head -20'
alias gb='git branch -a'

# Fix vim versioning
# TODO consider using variable latest to assist updating
# alias vim='/usr/local/Cellar/vim/7.4.2109/bin/vim'

# Tab complete case insensitive
bind "set completion-ignore-case on"
# When multiple matches, always show all matches
bind "set show-all-if-ambiguous on"

# Common typing mistakes
alias sl='ls'

# FZF (for fuzzyfinding) config
export FZF_DEFAULT_OPTS='--height 40%'
export FZF_DEFAULT_COMMAND='ag -g ""'
alias vf='vim $(fzf)'

# Simple but not thourough (e.g. cannot -p)
mkcd () {
    mkdir "$1"
    cd "$1"
}

# List/ change screenshot directory
# Only works if you pass an absolute path
screenshots () {
    if [[ -z $1 ]]; then
        defaults read com.apple.screencapture location
    elif [[ -d $1 ]]; then
        defaults write com.apple.screencapture location $1
        killall SystemUIServer
    else
        echo "Not a valid directory"
    fi
}

